<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Twitter_Clone</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
    <Compile Remove="ConsoleApp1\**\*.cs" />
  </ItemGroup>

</Project>
